name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    # uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Authenticate with pub.dev via OIDC
        run: dart pub login --verbose

      - name: Publish to pub.dev
        run: dart pub publish --skip-validation --force