
name: Publish to pub.dev

on:
  push:
    branches:
      - release

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Check code style
        run: dart analyze

      - name: Publish to pub.dev
        run: dart pub publish --force
